config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "lists#index"
  get "lists", to: "lists#index"
  get "lists/new", to: "lists#new"
  post "lists", to: "lists#create"
  get "lists/:id", to: "lists#show", as: :list
  patch "movies/:id/bookmark", to: "movies#bookmark", as: :bookmark_movie
  delete "movies/:id/bookmark", to: "movies#unbookmark", as: :unbookmark_movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_all_lists

  def index
  end

  def new
    @list = List.new

  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def find_all_lists
    @lists = List.all
  end

  def list_params
    params.require(:list).permit(:name, :list_url)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def bookmark
    @movie = Movie.find(params[:id])
    @bookmark = Bookmark.new
    @bookmark.movie = @movie
    @bookmark.list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(params[:list_id])
    else
      render :show
    end
  end

  def unbookmark
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%# Navbar %>
        <a class="navbar-brand" href=<%= root_path %>>🎦 MyWatchLists.com</a>
        <%# Toggler %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%# Navbar colapse %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <%# Navbar list %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <%# Home %>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href=<%= lists_new_path %>>Create a new list</a>
            </li>
            <%# Link %>
            <%# Dropdown %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Show all my lists
              </a>
              <ul class="dropdown-menu">
                <% @lists.each do |list| %>
                  <li class="dropdown-item"><%= link_to list.name, list_path(list) %></li>
                  <li><hr class="dropdown-divider"></li>
                <% end %>
                <li> <%= link_to "NEW LIST", lists_new_path %></li>
              </ul>
            </li>
          </ul>
          <%# <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> %>
        </div>
      </div>
    </nav>
      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="lists_background">
  <h1>Your Lists</h1>
</div>
<div class="container card_container">
  <% @lists.each do |list| %>
    <div class="card" style="width: 18rem;">
      <img src='<%= list.list_url %>' class="card-img-top" alt="List poster">
      <div class="card-body">
        <h5 class="card-title"><%= list.name %></h5>
        <a href=<%= list_path(list) %> class="btn btn-primary">Open list 🍿</a>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h2>Create your new list:</h2>
  <%# how to make this form create a new list in my database? %>
  <%= simple_form_for @list, url: lists_path, method: :post do |f| %>
    <%= f.input :name %>
    <%= f.input :list_url %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>